phases:
- phase: Windows
  queue: 
    name: Hosted VS2017
    timeoutInMinutes: 120
  steps:
  - template: Build/steps.yml
    parameters:
      os: 'Windows'

- phase: Linux
  queue: 
    name: Hosted Linux Preview
    timeoutInMinutes: 120
  steps:
  - template: Build/steps.yml
    parameters:
      os: 'Linux'

- phase: macOS
  queue: 
    name: Hosted macOS Preview
    timeoutInMinutes: 120
  steps:
  - template: Build/steps.yml
    parameters:
      os: 'macOS'
