jobs:

################################################################################
- job: Windows
################################################################################
  displayName: Windows
  timeoutInMinutes: 180
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: Build/steps.yml
    parameters:
      os: 'Windows'

################################################################################
- job: Linux
################################################################################
  displayName: Linux (Ubuntu)
  timeoutInMinutes: 180
  pool:
    vmImage: 'ubuntu-16.04'    
  steps:
  - template: Build/steps.yml
    parameters:
      os: 'Linux'

################################################################################
- job: macOS
################################################################################
  displayName: macOS
  timeoutInMinutes: 180
  pool: 
    vmImage: 'macOS-10.13'    
  steps:
  - template: Build/steps.yml
    parameters:
      os: 'macOS'
