jobs:

################################################################################
- job: Windows
################################################################################
  displayName: Windows
  timeoutInMinutes: 180
  pool:
    vmImage: windows-latest
  steps:
  - template: eng/steps.yml
    parameters:
      os: 'Windows'

################################################################################
- job: Linux
################################################################################
  displayName: Linux (Ubuntu)
  timeoutInMinutes: 180
  pool:
    vmImage: ubuntu-22.04
  steps:
  - template: eng/steps.yml
    parameters:
      os: 'Linux'

################################################################################
- job: macOS
################################################################################
  displayName: macOS
  timeoutInMinutes: 180
  pool:
    vmImage: macOS-latest
  steps:
  - template: eng/steps.yml
    parameters:
      os: 'macOS'
