# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
#version: 3.0.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
#branches:
  # whitelist
  # Setting this prevents PRs from being auto-built
  #only:
   # - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# build cache to preserve files/folders between builds
cache:
  - '%LocalAppData%\NuGet\Cache'

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
  - git submodule update --init --recursive
  - ps: $xml = [xml] (Get-Content CurrentVersion.props); $major = $xml.Project.PropertyGroup.MajorVersion; $minor = $xml.Project.PropertyGroup.MinorVersion; $micro = $xml.Project.PropertyGroup.MicroVersion; $serial = $xml.Project.PropertyGroup.ReleaseSerial; Update-AppveyorBuild -Version "$($major).$($minor).$($micro).$($serial)-$($env:APPVEYOR_BUILD_NUMBER)".replace(" ","")

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - .\make.cmd

# to disable automatic builds
#build: off

# to run your custom scripts instead of automatic tests
test_script:
  - .\make.cmd ngen
  - .\make.cmd test-all

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

#artifacts:

#  # pushing a single file
#  - path: test.zip

#  # pushing entire folder as a zip archive
#  - path: logs

#  # pushing all *.nupkg files in build directory recursively
#  - path: '**\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
#deploy:

#    # Deploying to NuGet feed
#  - provider: NuGet
#    server: https://my.nuget.server/feed
#    api_key:
#      secure: FYWX6NfjZIVw==
#    skip_symbols: false
#    symbol_server: https://your.symbol.server/feed
#    artifact: MyPackage.nupkg

#    # Deploy to GitHub Releases
#  - provider: GitHub
#    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
#    draft: false
#    prerelease: false
#    on:
#      branch: master                # release from master branch only
#      appveyor_repo_tag: true       # deploy on tag push only

#        global handlers          #
#---------------------------------#

on_failure:
  - ps: Write-Host "Uploading test results"
  - ps: $wc = New-Object 'System.Net.WebClient'; foreach($file in (Get-ChildItem -Include *-result.xml -Recurse)) { $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $file) }
  - ps: Write-Host "Done uploading test results"
  
on_success:
  - ps: Write-Host "Uploading test results"
  - ps: $wc = New-Object 'System.Net.WebClient'; foreach($file in (Get-ChildItem -Include *-result.xml -Recurse)) { $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $file) }
  - ps: Write-Host "Done uploading test results"


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - developers+int+211+854770831703316759@ironpython.groups.io
    subject: 'IronPython3 Build {{status}}'
    #message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true

  # Gitter
  - provider: Webhook
    url: https://webhooks.gitter.im/e/b21a2ccce686293e02f7 
    #headers: ? message payload? how to differentiate projects?
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
