# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
#version: 3.0.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# build cache to preserve files/folders between builds
cache:
  - '%LocalAppData%\NuGet\Cache'

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

install:
  - ps: (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe', 'C:\Tools\NuGet\NuGet.exe')

# scripts to run before build
before_build:
  - git submodule update --init --recursive
  - nuget restore
  - ps: $xml = [xml] (Get-Content CurrentVersion.props); $major = $xml.Project.PropertyGroup.MajorVersion; $minor = $xml.Project.PropertyGroup.MinorVersion; $micro = $xml.Project.PropertyGroup.MicroVersion; $serial = $xml.Project.PropertyGroup.ReleaseSerial; Update-AppveyorBuild -Version "$($major).$($minor).$($micro).$($serial)-$($env:APPVEYOR_BUILD_NUMBER)".replace(" ","")

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:
  - ps: .\make.ps1 package

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: .\make.ps1

# to run your custom scripts instead of automatic tests
test_script:
  - ps: .\make.ps1 ngen
  - ps: .\make.ps1 test-all

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Package/Release/Packages/**/*.zip
    name: Zip Package
    type: Zip

  - path: Package/Release/Packages/**/*.nupkg
    name: NuGet Package
    type: NuGetPackage

  - path: build-*.binlog
    name: Binary Build Log
    type: File


on_failure:
  - ps: Write-Host "Uploading test results"
  - ps: $wc = New-Object 'System.Net.WebClient'; foreach($file in (Get-ChildItem -Include '*-result.xml' -Recurse)) { $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $file) }
  - ps: $wc = New-Object 'System.Net.WebClient'; foreach($file in (Get-ChildItem -Include '*.trx' -Recurse)) { $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", $file) }
  - ps: Write-Host "Done uploading test results"

on_success:
  - ps: Write-Host "Uploading test results"
  - ps: $wc = New-Object 'System.Net.WebClient'; foreach($file in (Get-ChildItem -Include '*-result.xml' -Recurse)) { $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $file) }
  - ps: $wc = New-Object 'System.Net.WebClient'; foreach($file in (Get-ChildItem -Include '*.trx' -Recurse)) { $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", $file) }
  - ps: Write-Host "Done uploading test results"


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - developers+int+211+854770831703316759@ironpython.groups.io
    subject: 'IronPython3 Build {{status}}'
    on_build_status_changed: true

  # Gitter
  - provider: Webhook
    url: https://webhooks.gitter.im/e/b21a2ccce686293e02f7 
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
