// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using System;
using System.Runtime.Serialization;

namespace IronPython.Runtime.Exceptions {
#if !FEATURE_WARNING_EXCEPTION
    #region Generated WarningException

    // *** BEGIN GENERATED CODE ***
    // generated by function: gen_one_exception_specialized from: generate_exceptions.py


    [Serializable]
    public class WarningException : Exception {
        public WarningException() : base() { }
        public WarningException(string msg) : base(msg) { }
        public WarningException(string message, Exception innerException)
            : base(message, innerException) {
        }
#if FEATURE_SERIALIZATION
        protected WarningException(SerializationInfo info, StreamingContext context) : base(info, context) { }
#endif
    }


    // *** END GENERATED CODE ***

    #endregion
#endif
}
