// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

#nullable enable

using System;

namespace IronPython.Modules {
    public static partial class PythonMath {
        #region Generated math functions

        // *** BEGIN GENERATED CODE ***
        // generated by function: gen_funcs from: generate_math.py

        public static double cos(double v0) {
            return Check(v0, Math.Cos(v0));
        }
        public static double sin(double v0) {
            return Check(v0, Math.Sin(v0));
        }
        public static double tan(double v0) {
            return Check(v0, Math.Tan(v0));
        }
        public static double cosh(double v0) {
            return Check(v0, Math.Cosh(v0));
        }
        public static double sinh(double v0) {
            return Check(v0, Math.Sinh(v0));
        }
        public static double tanh(double v0) {
            return Check(v0, Math.Tanh(v0));
        }
        public static double acos(double v0) {
            return Check(v0, Math.Acos(v0));
        }
        public static double asin(double v0) {
            return Check(v0, Math.Asin(v0));
        }
        public static double atan(double v0) {
            return Check(v0, Math.Atan(v0));
        }
        public static double fabs(double v0) {
            return Check(v0, Math.Abs(v0));
        }
        public static double sqrt(double v0) {
            return Check(v0, Math.Sqrt(v0));
        }
        public static double exp(double v0) {
            return Check(v0, Math.Exp(v0));
        }

        // *** END GENERATED CODE ***

        #endregion
    }
}
